{
	"version": 1504527197,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/objetos-sheet0.png",
		"images/fita-sheet0.png",
		"images/quadro-sheet0.png",
		"images/tv-sheet0.png",
		"images/tv1-sheet0.png",
		"images/mesa1-sheet0.png",
		"images/mesatv2-sheet0.png",
		"images/aquario-sheet0.png",
		"images/aquario2-sheet0.png",
		"images/luz-sheet0.png",
		"images/luz1-sheet0.png",
		"images/letreiro-sheet0.png",
		"images/fita1-sheet0.png",
		"images/fita2-sheet0.png",
		"images/spawn-sheet0.png",
		"images/letra-sheet0.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/sofa-sheet0.png",
		"images/sofa1-sheet0.png",
		"images/tapete-sheet0.png",
		"images/mesa-sheet0.png",
		"images/mesa2-sheet0.png",
		"images/pia-sheet0.png",
		"images/fogao-sheet0.png",
		"images/esquerda-sheet0.png",
		"images/direita-sheet0.png",
		"images/cima-sheet0.png",
		"images/baixo-sheet0.png",
		"images/piso.png",
		"images/spawnf-sheet0.png",
		"images/logo-sheet0.png",
		"images/porta1-sheet0.png",
		"images/porta0-sheet0.png",
		"images/porta2-sheet0.png",
		"images/geladeira-sheet0.png",
		"images/mesacoz-sheet0.png",
		"images/pararfita-sheet0.png",
		"images/obj1-sheet0.png",
		"images/obj2-sheet0.png",
		"images/obj3-sheet0.png",
		"images/cama-sheet0.png",
		"images/abajur-sheet0.png",
		"images/mesacomp-sheet0.png",
		"images/livros-sheet0.png",
		"images/computador-sheet0.png",
		"images/porta3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground3.png",
		"images/rpgtile-sheet0.png",
		"images/rpgtile2-sheet0.png",
		"images/rpgtile3-sheet0.png",
		"images/rpgtile4-sheet0.png",
		"images/rpgtile5-sheet0.png",
		"images/rpgtile6-sheet0.png",
		"images/rpgtile7-sheet0.png",
		"images/rpgtile8-sheet0.png",
		"images/rpgtile9-sheet0.png",
		"images/tile_-sheet0.png",
		"images/tile_2-sheet0.png",
		"images/tile_3-sheet0.png",
		"images/tile_4-sheet0.png",
		"images/sobremesa-sheet0.png",
		"images/chao-sheet0.png",
		"images/b1-sheet0.png",
		"images/botao-sheet0.png",
		"images/cell-sheet0.png",
		"images/telacelular-sheet0.png",
		"images/snumb-sheet0.png",
		"images/bligar-sheet0.png",
		"images/chao1-sheet0.png",
		"images/q1-sheet0.png",
		"images/q1-sheet1.png",
		"images/quadro1-sheet0.png",
		"images/quadro3-sheet0.png",
		"images/tmorte.png",
		"images/tdesenv-sheet0.png",
		"images/logo2-sheet0.png",
		"images/play0-sheet0.png",
		"images/menu-sheet0.png",
		"media/audio das fases.m4a",
		"media/audio das fases.ogg",
		"media/click1.m4a",
		"media/click1.ogg",
		"media/colocar atras do audio de gryci.m4a",
		"media/colocar atras do audio de gryci.ogg",
		"media/fase cozinha.m4a",
		"media/fase cozinha.ogg",
		"media/fase quarto.m4a",
		"media/fase quarto.ogg",
		"media/fase sala.m4a",
		"media/fase sala.ogg",
		"media/introducao.m4a",
		"media/introducao.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}